### ISSUE TITLE
目录生成的时候错误

### ISSUE THREAD

**Issue by latexstudio** [qinglee/maoxuan#2]
l.12 \tableofcontents
                     
? 
! Argument of \maoxuan@saved@contentsline has an extra }.
<inserted text> 
                \par 
l.12 \tableofcontents
                     
? 
Runaway argument?
! Paragraph ended before \maoxuan@saved@contentsline was complete.
<to be read again> 
                   \par 
l.12 \tableofcontents
第一遍编译没有问题了，生成目录的时候报错信息如上，环境texlive2016.

**Comment by qinglee** [comment]
对 `\@chapter` 补丁失败造成的，已修正。
