### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ncihnegn** [qinglee/maoxuan#3]
! Missing number, treated as zero.
<to be read again>
                   _
l.517 ...帝国主义的策略}{23}和\mxnotex{24}

mxnotex 命令的问题。 
最新的texlive。
λ xelatex
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
**

**Comment by qinglee** [comment]
xeCJK 的问题，将在下一版本中修复。
