### ISSUE TITLE
Xelatex always asks for rerun

### ISSUE THREAD

**Issue by ncihnegn** [qinglee/maoxuan#4]
Xelatex always gives this no matter how many times I run:

> Package rerunfilecheck Warning: File `maoxuan.toc' has changed. Rerun.

It could be a xelatex bug. But I have seen it only for this document so far.
What is so special about this document?

**Comment by qinglee** [comment]
Please check out the latest version. I had fixed this issue in https://github.com/qinglee/maoxuan/commit/598f9ce441a6d52ecb58b8a8c74573dd990cdd51 .
